# Ragequit Plugin by Rasmus Henneken
#
# %player% includes pre- and suffixes
# Use & for colors and formatting

ragequit_message: '%player% ragequit. What a noob. :)'
kick_message: '&dBut why???'
no_permission: '&d&l.&f&lc&d&lu&f&lt &8â™ &fNo permission!'